apiVersion: v1
kind: Service
metadata:
  name: btc-price-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5000
  selector:
    app: btc-price-service